daemon off;
worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events {
    worker_connections 64;
}
http {
    access_log off;
    server {
        listen 8080;
        location / {
            default_type text/plain;
            return 200 "nginx is running\n";
        }
    }
}
