# Тимчасовий файл створено в одному шарі, а видалено в наступному.
# Шар із файлом лишається в образі, тому розмір не зменшується.
FROM alpine:3.24
RUN dd if=/dev/urandom of=/tmp/big.bin bs=1M count=40
RUN rm /tmp/big.bin
CMD ["sh"]
